  CREATE TABLE "DOSTEPNOSC" 
   (	"DOSTEPNOSCID" NUMBER, 
	"DATA" DATE NOT NULL ENABLE, 
	"GODZINAOD" NUMBER(7,5) NOT NULL ENABLE, 
	"GODZINADO" NUMBER(7,5) NOT NULL ENABLE, 
	"SALAID" NUMBER, 
	"WYPOSAZENIEID" NUMBER, 
	 PRIMARY KEY ("DOSTEPNOSCID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "EGZEMPLARZ" 
   (	"EGZEMPLARZID" NUMBER, 
	"STATUS" VARCHAR2(50) NOT NULL ENABLE, 
	"WYDANIEID" NUMBER NOT NULL ENABLE, 
	 PRIMARY KEY ("EGZEMPLARZID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "HTMLDB_PLAN_TABLE" 
   (	"STATEMENT_ID" VARCHAR2(30), 
	"PLAN_ID" NUMBER, 
	"TIMESTAMP" DATE, 
	"REMARKS" VARCHAR2(4000), 
	"OPERATION" VARCHAR2(30), 
	"OPTIONS" VARCHAR2(255), 
	"OBJECT_NODE" VARCHAR2(128), 
	"OBJECT_OWNER" VARCHAR2(128), 
	"OBJECT_NAME" VARCHAR2(128), 
	"OBJECT_ALIAS" VARCHAR2(261), 
	"OBJECT_INSTANCE" NUMBER(*,0), 
	"OBJECT_TYPE" VARCHAR2(128), 
	"OPTIMIZER" VARCHAR2(255), 
	"SEARCH_COLUMNS" NUMBER, 
	"ID" NUMBER(*,0), 
	"PARENT_ID" NUMBER(*,0), 
	"DEPTH" NUMBER(*,0), 
	"POSITION" NUMBER(*,0), 
	"COST" NUMBER(*,0), 
	"CARDINALITY" NUMBER(*,0), 
	"BYTES" NUMBER(*,0), 
	"OTHER_TAG" VARCHAR2(255), 
	"PARTITION_START" VARCHAR2(255), 
	"PARTITION_STOP" VARCHAR2(255), 
	"PARTITION_ID" NUMBER(*,0), 
	"OTHER" LONG, 
	"DISTRIBUTION" VARCHAR2(30), 
	"CPU_COST" NUMBER(*,0), 
	"IO_COST" NUMBER(*,0), 
	"TEMP_SPACE" NUMBER(*,0), 
	"ACCESS_PREDICATES" VARCHAR2(4000), 
	"FILTER_PREDICATES" VARCHAR2(4000), 
	"PROJECTION" VARCHAR2(4000), 
	"TIME" NUMBER(*,0), 
	"QBLOCK_NAME" VARCHAR2(128)
   ) ;

  CREATE TABLE "KARA" 
   (	"KARAID" NUMBER, 
	"KWOTA" NUMBER(10,2) NOT NULL ENABLE, 
	"POWOD" VARCHAR2(255) NOT NULL ENABLE, 
	"DATANALOZENIA" DATE NOT NULL ENABLE, 
	"WYPOZYCZENIEID" NUMBER NOT NULL ENABLE, 
	 PRIMARY KEY ("KARAID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "KOMUNIKAT" 
   (	"KOMUNIKATID" NUMBER, 
	"TYTUL" VARCHAR2(255) NOT NULL ENABLE, 
	"TRESC" VARCHAR2(1024) NOT NULL ENABLE, 
	"ZDJECIE" VARCHAR2(255), 
	"DATAKOMUNIKATU" DATE NOT NULL ENABLE, 
	"UZYTKOWNIKID" NUMBER NOT NULL ENABLE, 
	 PRIMARY KEY ("KOMUNIKATID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "PUBLIKACJA" 
   (	"PUBLIKACJAID" NUMBER, 
	"TYTUL" VARCHAR2(255) NOT NULL ENABLE, 
	"GATUNEK" VARCHAR2(100) NOT NULL ENABLE, 
	"CYKL" VARCHAR2(255), 
	 PRIMARY KEY ("PUBLIKACJAID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "RECENZJA" 
   (	"RECENZJAID" NUMBER, 
	"OCENA" NUMBER NOT NULL ENABLE, 
	"KOMENTARZ" VARCHAR2(2048) NOT NULL ENABLE, 
	"DATARECENZJI" DATE NOT NULL ENABLE, 
	"WYDANIEID" NUMBER NOT NULL ENABLE, 
	"UZYTKOWNIKID" NUMBER NOT NULL ENABLE, 
	 CHECK (Ocena BETWEEN 1 AND 10) ENABLE, 
	 PRIMARY KEY ("RECENZJAID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "REZERWACJA" 
   (	"REZERWACJAID" NUMBER, 
	"DATAREZERWACJI" DATE NOT NULL ENABLE, 
	"GODZINAOD" NUMBER(7,5) NOT NULL ENABLE, 
	"GODZINADO" NUMBER(7,5) NOT NULL ENABLE, 
	"UZYTKOWNIKID" NUMBER NOT NULL ENABLE, 
	"SALAID" NUMBER, 
	"WYPOSAZENIEID" NUMBER, 
	 PRIMARY KEY ("REZERWACJAID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "SALA" 
   (	"SALAID" NUMBER, 
	"NAZWA" VARCHAR2(255) NOT NULL ENABLE, 
	"OPIS" VARCHAR2(1024) NOT NULL ENABLE, 
	"MAKSYMALNAPOJEMNOSC" NUMBER NOT NULL ENABLE, 
	"ZDJECIE" VARCHAR2(255) NOT NULL ENABLE, 
	 PRIMARY KEY ("SALAID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "SUGESTIA" 
   (	"SUGESTIAID" NUMBER, 
	"TYTULPROPOZYCJI" VARCHAR2(255) NOT NULL ENABLE, 
	"AUTORPROPOZYCJI" VARCHAR2(255) NOT NULL ENABLE, 
	"GATUNEKPROPOZYCJI" VARCHAR2(100) NOT NULL ENABLE, 
	"ROKWYDANIA" NUMBER NOT NULL ENABLE, 
	"TYPPUBLIKACJI" VARCHAR2(100) NOT NULL ENABLE, 
	"ARGUMENTACJA" VARCHAR2(1024), 
	"DATASUGESTII" DATE NOT NULL ENABLE, 
	"UZYTKOWNIKID" NUMBER NOT NULL ENABLE, 
	"STATUS" VARCHAR2(50) DEFAULT 'Nieprzetworzone' NOT NULL ENABLE, 
	 PRIMARY KEY ("SUGESTIAID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "UZYTKOWNIK" 
   (	"UZYTKOWNIKID" NUMBER, 
	"IMIE" VARCHAR2(255) NOT NULL ENABLE, 
	"NAZWISKO" VARCHAR2(255) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(255) NOT NULL ENABLE, 
	"HASLO" VARCHAR2(255) NOT NULL ENABLE, 
	"DATAREJESTRACJI" DATE NOT NULL ENABLE, 
	"STATUSKONTA" VARCHAR2(50) NOT NULL ENABLE, 
	"ZDJECIE" VARCHAR2(255) NOT NULL ENABLE, 
	 PRIMARY KEY ("UZYTKOWNIKID")
  USING INDEX  ENABLE, 
	 UNIQUE ("EMAIL")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "WYDANIE" 
   (	"WYDANIEID" NUMBER, 
	"TYPWYDANIA" VARCHAR2(50) NOT NULL ENABLE, 
	"OKLADKA" VARCHAR2(255) NOT NULL ENABLE, 
	"ROK" NUMBER NOT NULL ENABLE, 
	"AUTOR" VARCHAR2(255) NOT NULL ENABLE, 
	"PODGATUNEK" VARCHAR2(50), 
	"CZASTRWANIA" NUMBER, 
	"PRODUKCJA" VARCHAR2(255), 
	"ISBN" VARCHAR2(13), 
	"WYDAWNICTWO" VARCHAR2(255), 
	"LICZBASTRON" NUMBER, 
	"PUBLIKACJAID" NUMBER NOT NULL ENABLE, 
	"OPIS" VARCHAR2(2048) NOT NULL ENABLE, 
	 PRIMARY KEY ("WYDANIEID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "WYPOSAZENIE" 
   (	"WYPOSAZENIEID" NUMBER, 
	"NAZWA" VARCHAR2(255) NOT NULL ENABLE, 
	"OPIS" VARCHAR2(1024) NOT NULL ENABLE, 
	"TYP" VARCHAR2(255) NOT NULL ENABLE, 
	"ZDJECIE" VARCHAR2(255) NOT NULL ENABLE, 
	 PRIMARY KEY ("WYPOSAZENIEID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "WYPOZYCZENIE" 
   (	"WYPOZYCZENIEID" NUMBER, 
	"DATAWYPOZYCZENIA" DATE NOT NULL ENABLE, 
	"DATAZWROTU" DATE, 
	"MAKSYMALNADATAZWROTU" DATE NOT NULL ENABLE, 
	"STATUS" VARCHAR2(50) NOT NULL ENABLE, 
	"EGZEMPLARZID" NUMBER NOT NULL ENABLE, 
	"UZYTKOWNIKID" NUMBER NOT NULL ENABLE, 
	 PRIMARY KEY ("WYPOZYCZENIEID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "ZAMOWIENIE" 
   (	"ZAMOWIENIEID" NUMBER, 
	"DATADODANIA" DATE NOT NULL ENABLE, 
	"STATUS" VARCHAR2(50) NOT NULL ENABLE, 
	"SUGESTIAID" NUMBER NOT NULL ENABLE, 
	 PRIMARY KEY ("ZAMOWIENIEID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "DOSTEPNOSC" ADD CONSTRAINT "DOSTEPNOSC_CON" FOREIGN KEY ("SALAID")
	  REFERENCES "SALA" ("SALAID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "DOSTEPNOSC" ADD CONSTRAINT "DOSTEPNOSC_CON2" FOREIGN KEY ("WYPOSAZENIEID")
	  REFERENCES "WYPOSAZENIE" ("WYPOSAZENIEID") ON DELETE CASCADE ENABLE;


  ALTER TABLE "EGZEMPLARZ" ADD FOREIGN KEY ("WYDANIEID")
	  REFERENCES "WYDANIE" ("WYDANIEID") ON DELETE CASCADE ENABLE;


  ALTER TABLE "KARA" ADD CONSTRAINT "KARA_CON" FOREIGN KEY ("WYPOZYCZENIEID")
	  REFERENCES "WYPOZYCZENIE" ("WYPOZYCZENIEID") ON DELETE CASCADE ENABLE;


  ALTER TABLE "KOMUNIKAT" ADD FOREIGN KEY ("UZYTKOWNIKID")
	  REFERENCES "UZYTKOWNIK" ("UZYTKOWNIKID") ENABLE;


  ALTER TABLE "RECENZJA" ADD CONSTRAINT "RECENZJA_CON" FOREIGN KEY ("WYDANIEID")
	  REFERENCES "WYDANIE" ("WYDANIEID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "RECENZJA" ADD FOREIGN KEY ("UZYTKOWNIKID")
	  REFERENCES "UZYTKOWNIK" ("UZYTKOWNIKID") ENABLE;


  ALTER TABLE "REZERWACJA" ADD CONSTRAINT "REZERWACJA_CON" FOREIGN KEY ("WYPOSAZENIEID")
	  REFERENCES "WYPOSAZENIE" ("WYPOSAZENIEID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "REZERWACJA" ADD CONSTRAINT "REZERWACJA_CON_SALA" FOREIGN KEY ("SALAID")
	  REFERENCES "SALA" ("SALAID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "REZERWACJA" ADD FOREIGN KEY ("UZYTKOWNIKID")
	  REFERENCES "UZYTKOWNIK" ("UZYTKOWNIKID") ENABLE;


  ALTER TABLE "SUGESTIA" ADD FOREIGN KEY ("UZYTKOWNIKID")
	  REFERENCES "UZYTKOWNIK" ("UZYTKOWNIKID") ENABLE;


  ALTER TABLE "WYDANIE" ADD FOREIGN KEY ("PUBLIKACJAID")
	  REFERENCES "PUBLIKACJA" ("PUBLIKACJAID") ON DELETE CASCADE ENABLE;


  ALTER TABLE "WYPOZYCZENIE" ADD FOREIGN KEY ("UZYTKOWNIKID")
	  REFERENCES "UZYTKOWNIK" ("UZYTKOWNIKID") ENABLE;
  ALTER TABLE "WYPOZYCZENIE" ADD CONSTRAINT "WYPOZYCZENIE_CON" FOREIGN KEY ("EGZEMPLARZID")
	  REFERENCES "EGZEMPLARZ" ("EGZEMPLARZID") ON DELETE CASCADE ENABLE;


  ALTER TABLE "ZAMOWIENIE" ADD FOREIGN KEY ("SUGESTIAID")
	  REFERENCES "SUGESTIA" ("SUGESTIAID") ENABLE;

